import { defineConfig } from 'vite'
import { VitePWA } from 'vite-plugin-pwa'
import ogPlugin from 'vite-plugin-open-graph'

export default defineConfig(({ mode }) => {
  const isProd = mode === 'production';
  return {
    // CRITICAL: Set this to your exact GitHub repository name wrapped in slashes
    base: '/',

    plugins: [

      ogPlugin({
        basic: {
          url: 'https://nethalastat.crunchcompanion.com', // Must be your live URL for correct OG tags
          title: 'Nethalastat - A Ker Nethalas Stat Tracker App',
          type: 'website',
          image: 'https://nethalastat.crunchcompanion.com/og-image.png', // Must be absolute URL
          description: 'Nethalastat is a stat tracking app for the solo RPG Ker Nethalas, built with PWA technology for offline use.',
        },
        twitter: {
          card: 'summary_large_image', // Forces Discord to show a large 16:9 card
          image: 'https://nethalastat.crunchcompanion.com/large-og-image.png',
        }
      }),

      VitePWA({ 
        registerType: 'prompt', // Prompts user to install when criteria are met
        injectRegister: 'inline', // Safely inlines the SW registration script
        workbox: {
          // Tells workbox to cache all assets generated by Vite
          globPatterns: ['**/*.{js,css,html,ico,png,svg,woff2}'],
        },
        manifest: {
          id: isProd ? 'com.crunchcompanion.nethalastat.app' : 'com.crunchcompanion.nethalastat.dev',
          name: 'Nethalastat - A Ker Nethalas Stat Tracker App',
          description: 'A stat tracking app for the solo RPG Ker Nethalas, built with PWA technology for offline use.',
          short_name: 'Nethalastat',
          theme_color: '#000000',
          
          icons: [
            {
              src: './pwa-192x192.png',
              sizes: '192x192',
              type: 'image/png'
            },
            {
              src: './pwa-512x512.png',
              sizes: '512x512',
              type: 'image/png'
            }
          ],
          screenshots: [
            {
              src: './screenshot-mobile.png',
              sizes: '442x978',
              type: 'image/png',
              form_factor: 'narrow',
              label: 'Nethalastat mobile stat tracker'
            },
            {
              src: './screenshot-desktop.png',
              sizes: '596x998',
              type: 'image/png',
              form_factor: 'wide',
              label: 'Nethalastat stat tracker'
            }
          ]
        },


        devOptions: {
          enabled: true
        }
      })
    ]
  }
})  