import { defineConfig } from 'vite'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig(({ mode }) => {
  return {
    // CRITICAL: Set this to your exact GitHub repository name wrapped in slashes
    base: mode === 'production' ? '/your-repo-name/' : '/',

    plugins: [
      VitePWA({ 
        registerType: 'autoUpdate',
        injectRegister: 'inline', // Safely inlines the SW registration script
        workbox: {
          // Tells workbox to cache all assets generated by Vite
          globPatterns: ['**/*.{js,css,html,ico,png,svg,woff2}'],
        },
        manifest: {
          name: 'Nethalastat PWA',
          short_name: 'nPWA',
          theme_color: '#000000',
          
          icons: [
            {
              src: '/icon-192x192.png',
              sizes: '192x192',
              type: 'image/png'
            },
            {
              src: '/icon-512x512.png',
              sizes: '512x512',
              type: 'image/png'
            }
          ]
        },
        devOptions: {
          enabled: true
        }
      })
    ]
  }
})  