import { defineConfig } from 'vite'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig(({ mode }) => {
  const isProd = mode === 'production';
  return {
    // CRITICAL: Set this to your exact GitHub repository name wrapped in slashes
    base: '/',

    plugins: [
      VitePWA({ 
        registerType: 'autoUpdate',
        injectRegister: 'inline', // Safely inlines the SW registration script
        workbox: {
          // Tells workbox to cache all assets generated by Vite
          globPatterns: ['**/*.{js,css,html,ico,png,svg,woff2}'],
        },
        manifest: {
          id: isProd ? 'com.crunchcompanion.nethalastat.app' : 'com.crunchcompanion.nethalastat.dev',
          name: 'Nethalastat',
          short_name: 'Nstat',
          theme_color: '#000000',
          
          icons: [
            {
              src: './pwa-192x192.png',
              sizes: '192x192',
              type: 'image/png'
            },
            {
              src: './pwa-512x512.png',
              sizes: '512x512',
              type: 'image/png'
            }
          ],
          screenshots: [
            {
              src: './screenshot-mobile.png',
              sizes: '442x978',
              type: 'image/png',
              form_factor: 'narrow',
              label: 'Nethalastat mobile stat tracker'
            },
            {
              src: './screenshot-desktop.png',
              sizes: '596x998',
              type: 'image/png',
              form_factor: 'wide',
              label: 'Nethalastat stat tracker'
            }
          ]
        },


        devOptions: {
          enabled: true
        }
      })
    ]
  }
})  